# Generated by Django 4.2.7 on 2024-01-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/profiles/default-avatar.png', upload_to='images/profiles', verbose_name='آواتار'),
        ),
    ]
