# Generated by Django 4.2.7 on 2023-11-09 11:58

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('is_enable', models.BooleanField(default=True, verbose_name='فعال')),
                ('slug', models.SlugField(blank=True, max_length=300, verbose_name='اسلاگ')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='product.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ProductColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=300, unique=True, verbose_name='نام رنگ')),
                ('color_hex_code', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#000000', 'سیاه'), ('#FFFFFF', 'سفید'), ('#FF0000', 'قرمز'), ('#0000FF', 'آبی'), ('#008000', 'سبز'), ('#FFFF00', 'زرد'), ('#FFA500', 'نارنجی'), ('#800080', 'بنفش'), ('#FFC0CB', 'صورتی'), ('#964B00', 'قهوه ای'), ('#808080', 'طوسی')], verbose_name='کد hex رنگ')),
                ('stock_count', models.PositiveBigIntegerField(verbose_name='تعداد موجودی')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=300, verbose_name='اسلاگ')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('off', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(100.0)], verbose_name='تخفیف')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_time', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='اندازه')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category', verbose_name='دسته بندی')),
                ('color_variant', models.ManyToManyField(related_name='products', to='product.productcolorvariant')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_time', '-updated_time'],
                'indexes': [models.Index(fields=['-created_time'], name='product_pro_created_8da700_idx')],
            },
        ),
    ]
