# Generated by Django 4.2.7 on 2023-12-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorvariant',
            name='color_name',
            field=models.CharField(max_length=300, verbose_name='نام رنگ'),
        ),
    ]
