# Generated by Django 4.2.7 on 2023-12-15 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productcolorvariant_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_variant',
        ),
        migrations.AddField(
            model_name='productcolorvariant',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='product.product', verbose_name='محصول'),
        ),
    ]
