# Generated by Django 4.2.7 on 2024-01-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصول'},
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='توضیحات کوتاه درباره ی محصولات این سایت که در قسمت توضیحات محصول قرار می گیرد.', max_length=350, verbose_name='توضیحات کوتاه'),
            preserve_default=False,
        ),
    ]
