# Generated by Django 4.2.7 on 2024-01-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productgallery_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم')),
                ('data', models.CharField(max_length=100, verbose_name='داده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='product.product', verbose_name='مشخصات')),
            ],
            options={
                'verbose_name': 'مشخصات محصول',
            },
        ),
    ]
