# Generated by Django 4.2.7 on 2024-01-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_productcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='مشخصات'),
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
    ]
