# Generated by Django 4.2.7 on 2024-01-25 17:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_specification_delete_productspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolorvariant',
            name='off',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.0)], verbose_name='تخفیف'),
        ),
        migrations.AddField(
            model_name='productcolorvariant',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='product.productcomment', verbose_name='والد'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='text',
            field=models.TextField(verbose_name='نظر'),
        ),
    ]
