# Generated by Django 4.2.7 on 2024-03-18 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0019_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_products', to=settings.AUTH_USER_MODEL, verbose_name='کاربران علاقه\u200c\u200cمند به محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='viewers',
            field=models.ManyToManyField(editable=False, related_name='viewed_products', to=settings.AUTH_USER_MODEL, verbose_name='بازدید کنندگان'),
        ),
    ]
