# Generated by Django 4.2.7 on 2024-08-12 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0021_alter_product_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_products', to=settings.AUTH_USER_MODEL, verbose_name='پسندیده شده توسط'),
        ),
    ]
