# Generated by Django 4.2.7 on 2024-03-22 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0021_alter_product_liked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('products', models.ManyToManyField(blank=True, related_name='user_lists', to='product.product', verbose_name='محصولات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lists', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'unique_together': {('user', 'title')},
            },
        ),
    ]
