# Generated by Django 4.2.7 on 2024-08-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproductlist',
            options={'verbose_name': 'لیست محصولات کاربران', 'verbose_name_plural': 'لیست های محصولات کاربران'},
        ),
    ]
