# Generated by Django 4.2.7 on 2024-05-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('PR', 'پیشنهاد'), ('CR', 'انتقاد'), ('RP', 'گزارش')], max_length=2)),
                ('message', models.TextField(verbose_name='پیام')),
                ('name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('read_by_admin', models.BooleanField(default=False, verbose_name='خوانده شده توسط مدیر')),
                ('admin_answer', models.TextField(blank=True, null=True, verbose_name='پاسخ مدیر')),
            ],
            options={
                'verbose_name': 'تیکت ها',
            },
        ),
    ]
