# Generated by Django 4.2.7 on 2024-08-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'محصول سبد خرید', 'verbose_name_plural': 'محصولات سبد خرید'},
        ),
    ]
